rc.local wait time
rc.local wait time

diff --git a/debianims-as-root b/debianims-as-root
--- a/debianims-as-root
+++ b/debianims-as-root
@@ -89,6 +89,8 @@ echo "tmpfs           /tmp            tmpfs  nodev,nosuid,mode=1777     0 0" >> 
 mkdir -p /usr/bin
 cat <<EOF > /usr/bin/zramims
 #!/bin/bash
+# Wait for login to print
+/bin/sleep 10
 cores=\$(nproc --all)
 modprobe zram num_devices=\$cores
 swapoff -a
@@ -106,7 +108,28 @@ chmod +x /usr/bin/zramims
 # Write /etc/rc.local and make executable
 cat <<EOF > /etc/rc.local
 #!/bin/sh -e
+#
+# rc.local
+#
+# This script is executed at the end of each multiuser runlevel.
+# Make sure that the script will "exit 0" on success or any other
+# value on error.
+#
+# In order to enable or disable this script just change the execution
+# bits.
+#
+# By default this script does nothing.
+
+# Wait for the CPU to rest and for the log files to finish writing.
+/bin/sleep 10
+# Print the IP address
+_IP=$(hostname -I) || true
+if [ "$_IP" ]; then
+  printf "My IP address is %s\n" "$_IP"
+fi
+# Start zram swap
 /usr/bin/zramims &
+sync
 exit 0
 EOF
 chmod +x /etc/rc.local
